### ISSUE TITLE
Data Paging Hard coded to 50 rows - Paging not always triggered. 

### ISSUE THREAD

**Issue by DougAGault** [plug-ins-pro/enhanced_grid_pro#2]
Hey guys, 

While testing out Enhanced Grid Pro (EGP)  on our production data set (much larger and more complete than DEV) I found the following issues that could make EGP not well received by our users. 

First of all, the data paging that is built in to the plugin is hardcoded to only grab 50 rows per set. Only after a scroll event is detected does the grid retrieve the next set (of 50). This can be a problem for us as we have Full data sets that are 55 or 60 rows and we don't want the users to have to scroll/page to show them all.  We even have one circumstance of 650 rows in a full data set where it is extremely important for them to see the whole row set at once without having to page

The second problem is that the scroll event isn't always triggered.  I have one page where the EGP is the only control. On a Tall screen, the grid retrieves the first 50 rows, but stops there. However, after the data is loaded, the grid only covers 3/4 of the page. Trying to scroll does not trigger the scroll event and therefore doesn't trigger any more rows to be loaded. 

In hopes that I could override the paging functionality by talking directly to the underlying HandsOnTable object, I tried using the configuration option of `renderAllRows`  but this obviously doesn't take into account that the paging is happening in your Plugin/Wrapper code. 

I also looked for an exposed method that allowed me to manually raise a scroll event (or to force the next set of data to be loaded) and could not find anything. 

Requested Solution(s). 
1. Provide a plugin attribute for batch size (default it to 50 if you like, but don't limit it). 
2. Provide configuration option to allow for loading all rows despite the batch size. 

Please let  me know if I'm missing something here, but these changes are crucial to our ability to use EGP.

Thanks
DRW Holdings

**Comment by andraz-podobnik** [comment]
Hi Doug,

Thanks for letting us know about your issues.
We'll fix/improve both things you mentioned.

Thanks,
Andraz

p.s.
New version of EGP will be released soon. And both things you mentioned will be part of the release.

**Comment by andraz-podobnik** [comment]
Hi again,

as mentioned before, new version of Enhanced Grid Pro will be released soon.
Since we wanted to include this in the upcoming release (v23.2) we implemented this today...and here's how it's done:

**LOAD ALL DATA**
There's a new declarative attribute → “Load all data“. By default it's set to “No“. But when changed to “Yes“, Grid loads ALL the data returned by the query immediately (on page load).


**BATCH SIZE**
There’s no default anymore (before it was 50).

“batchSize“ value is now calculated based on the browser’s window height and the row height in Grid → This way it doesn’t matter how tall the screen is, users will always get enough rows to fill their screen.

Calculated “batchSize“ value is used on Initial load and every time the next batch of data is requested (triggered on scroll event).

However, developers can override “batchSize“ value using “Initialization JavaScript Function“ like this:

```
function (pOptions) {
    pOptions.batchSize = 20;
    return pOptions;
} 
```   
IMPORTANT: Value defined by developer will only be used when next batch of data is requested, and NOT on initial load.

**Comment by DougAGault** [comment]
Excellent. Thank you.  Yesterday Jackie and Dimitri game me a copy of the beta (which did not have these fixes in the plugin). I'll contact them to get another beta to make sure the fixes solve our use case!

Thank you for the quick response.

**Comment by DougAGault** [comment]
Jackie gave me the beta and it works GREAT. Solves this problem and the other issue that Jorge (@jrimblas) logged with COLUMN_OT. 

Thanks a million!
